#ifndef MACROS_H
#define MACROS_H

#define SPAWN_FREQUENCY 0
#define TURN_LEFT_FREQUENCY 30
#define DROP_VELOCITY_FREQUENCY 10

#define MAX_CARS 1000
#define NUMBER_OF_CROSSES 10

#define _1_VELOCITY (1)
#define _2_VELOCITY (_1_VELOCITY * 2)
#define _3_VELOCITY (_1_VELOCITY * 3)
#define _4_VELOCITY (_1_VELOCITY * 4)
#define _5_VELOCITY (_1_VELOCITY * 5)
#define _6_VELOCITY (_1_VELOCITY * 6)
#define _7_VELOCITY (_1_VELOCITY * 7)


#endif